/* Generated by Cython 0.27.3 */

#ifndef __PYX_HAVE__stacknet
#define __PYX_HAVE__stacknet


#ifndef __PYX_HAVE_API__stacknet

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *createInstanceStacknet(void);
__PYX_EXTERN_C void loadFinetuneModelForIns(PyObject *);
__PYX_EXTERN_C void insExtractFeature(PyObject *, PyObject *, PyObject *, PyObject *);
__PYX_EXTERN_C void predict_path_img(PyObject *, PyObject *);

#endif /* !__PYX_HAVE_API__stacknet */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initstacknet(void);
#else
PyMODINIT_FUNC PyInit_stacknet(void);
#endif

#endif /* !__PYX_HAVE__stacknet */
