/* Generated by Cython 0.27.3 */

#ifndef __PYX_HAVE__testmultithread
#define __PYX_HAVE__testmultithread


#ifndef __PYX_HAVE_API__testmultithread

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *createInstance(void);
__PYX_EXTERN_C PyObject *testprocess(PyObject *, PyObject *);

#endif /* !__PYX_HAVE_API__testmultithread */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inittestmultithread(void);
#else
PyMODINIT_FUNC PyInit_testmultithread(void);
#endif

#endif /* !__PYX_HAVE__testmultithread */
