/* Generated by Cython 0.27.3 */

#ifndef __PYX_HAVE__test
#define __PYX_HAVE__test


#ifndef __PYX_HAVE_API__test

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *createVGG(void);
__PYX_EXTERN_C PyObject *callPredict(PyObject *);

#endif /* !__PYX_HAVE_API__test */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inittest(void);
#else
PyMODINIT_FUNC PyInit_test(void);
#endif

#endif /* !__PYX_HAVE__test */
